# titanic data

## Importing the libraries

In [7]:
import numpy as np 
import pandas as pd  
import matplotlib.pyplot

## Importing the dataset

In [18]:
dataset = pd.read_csv("train.csv")
X = dataset.iloc[:, [ 2, 4, 5, 6, 7, 9] ].values
y = dataset.iloc[:, 1:2].values

In [19]:
data = pd.read_csv("test.csv")
X_pred = data.iloc[:, [ 1, 3, 4, 5, 6, 8] ].values
X_id = data.iloc[:, 0].values

In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:, [ 2, 5]])
X[:, [2, 5]] = imputer.transform(X[:, [ 2, 5]])
imputer1 = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer1 = imputer1.fit(X_train[:, [0, 3, 4]])
X[:, [0, 3, 4]] = imputer1.transform(X[:, [0, 3, 4]])

In [21]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X_pred[:, [ 2, 5]])
X_pred[:, [2, 5]] = imputer.transform(X_pred[:, [ 2, 5]])
imputer1 = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer1 = imputer.fit(X_pred[:, [0, 3, 4]])
X_pred[:, [0, 3, 4]] = imputer1.transform(X_pred[:, [0, 3, 4]])

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## Encoding categorical variables

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:, 1] = le.fit_transform(X_train[:, 1])
X_test[:, 1] = le.fit_transform(X_test[:, 1])
X_pred[:, 1] = le.fit_transform(X_pred[:, 1])

In [24]:
print(X_train)

[[3 1 19.0 0 0 14.5]
 [3 0 63.0 0 0 9.5875]
 [3 1 28.5 0 0 16.1]
 ...
 [3 1 51.0 0 0 7.75]
 [3 1 40.0 0 0 7.225]
 [3 1 29.69911764705882 0 0 7.8958]]


## Feature Selection


In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, [0, 2, 3, 4]] = sc.fit_transform(X_train[:, [0, 2, 3, 4]])
X_test[:, [0, 2, 3, 4]] = sc.fit_transform(X_test[:, [0, 2, 3, 4]])
X_pred[:, [0, 2, 3, 4]] = sc.fit_transform(X_pred[:, [0, 2, 3, 4]])

In [26]:
print(X_train)

[[0.8245867751551417 1 -0.7829778881428445 -0.4780764053919412
  -0.48263338564613173 14.5]
 [0.8245867751551417 0 2.5186285062753946 -0.4780764053919412
  -0.48263338564613173 9.5875]
 [0.8245867751551417 1 -0.07013105298436115 -0.4780764053919412
  -0.48263338564613173 16.1]
 ...
 [0.8245867751551417 1 1.6181903987067838 -0.4780764053919412
  -0.48263338564613173 7.75]
 [0.8245867751551417 1 0.7927888001022241 -0.4780764053919412
  -0.48263338564613173 7.225]
 [0.8245867751551417 1 0.01984654908811961 -0.4780764053919412
  -0.48263338564613173 7.8958]]


In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
y_pred = classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm  = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[89 22]
 [14 54]]


0.7988826815642458

In [39]:
y_result = classifier.predict(X_pred)

In [40]:
print(y_result)

[0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0
 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0
 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0
 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]
